2D Settings:
  Filename: bla
  Shots: 6000
  delay 1: 0.0
  max. Tau 2: 3.0
  min. Tau 2: -3.0
Sample:
  Annotations: ''
  Excitation: ''
  Sample: ''
  Solvent: ''
  Thickness: ''
list_of_samples:
- Cyclohexanol
- Phenylisocyanat
- TDI
list_of_solvents:
- Toluene
- THF
- H20
- D20
- DMSO
- None
