[project]
authors = ["Till Stensitzki <mail.till@gmx.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "messpy"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"
numba = ">=0.60.0,<0.61"
lmfit = ">=1.3.2,<2"
cffi = ">=1.17.0,<2"
pyside6 = ">=6.7.2,<7"
attrs = ">=24.2.0,<25"
wrapt = ">=1.16.0,<2"
pytest = ">=8.3.2,<9"
pytest-qt = ">=4.4.0,<5"
h5py = ">=3.11.0,<4"
loguru = ">=0.7.2,<0.8"
qtawesome = ">=1.3.1,<2"
qasync = ">=0.27.1,<0.28"
pyserial = ">=3.5,<4"
matplotlib = ">=3.9.2,<4"

[pypi-dependencies]
nicelib = ">=0.7.1, <0.8"
nidaqmx = ">=1.0.0, <2"
pyqtgraph = { git = "https://github.com/pyqtgraph/pyqtgraph" }
